### ISSUE TITLE
Checklist before 22 Feb 2019

### ISSUE THREAD

**Issue by weijie9512** [nyu-software-engineering/profile-photo-lookup#1]
Works to be done before (22 February 2019)

- [ ] Interview stakeholders
- [ ] Update CONTRIBUTING.md
- [ ] Update README.md
- [ ] Update REQUIREMENTS.md
